scripts/get_touchpad_info.sh: add srcipt for dumping TP info
3mdeb/fwdump-docker pull request #17
Opened 2022-04-06 14:57 UTC by mkopec

Signed-off-by: Michał Kopeć <michal.kopec@3mdeb.com>

2022-04-06 15:20 UTC, miczyg1 commented on scripts/get_touchpad_info.sh
> +apt-get install -y i2c-tools acpi-call-dkms
nope, this won't work. Add these to the Dockerfile

2022-04-06 15:22 UTC, miczyg1 commented on scripts/get_touchpad_info.sh
> +devpath=$(dmesg | grep hid-generic | awk '{print $4}' | cut -d ':' -f 1-3)
This also won't work as expected. dmesg from my PC:

```
[    1.512777] hid-generic 0003:413C:2113.0001: input,hidraw0: USB HID v1.11 Keyboard [Dell KB216 Wired Keyboard] on usb-0000:00:1a.0-1.1/input0
[    1.572904] hid-generic 0003:413C:2113.0002: input,hidraw1: USB HID v1.11 Device [Dell KB216 Wired Keyboard] on usb-0000:00:1a.0-1.1/input1
[    1.631587] hid-generic 0003:413C:301A.0003: input,hidraw2: USB HID v1.11 Mouse [PixArt Dell MS116 USB Optical Mouse] on usb-0000:00:1a.0-1.2/input0
```

We surely are not interested in USB HID devices...

2022-04-06 15:23 UTC, miczyg1 requested changes
Please at least build a container, add the touchpad detection script call to the getlogs.sh and test it on HW

2022-04-06 15:36 UTC, mkopec commented on scripts/get_touchpad_info.sh
> +devpath=$(dmesg | grep hid-generic | awk '{print $4}' | cut -d ':' -f 1-3)
right, added an extra grep on `I2C HID`. Also now the script exits if no i2c hid is found in dmesg

2022-04-06 21:34 UTC, macpijan commented
@miczyg1 

> Please at least build a container, add the touchpad detection script call to the getlogs.sh and test it on HW

This is tricky, as:
- we need access to i2c devices, which we currently do not have access to when running this container
- the `acpi-call-dkms` is a kernel module, which means it must be loaded on the host and match given kernel version - cannot be easily distributed inside of the container

I think we just dumped this script here for reference, but we may not be integrating it into the container, especially given that we want to replace it with different tools.

2022-04-06 21:56 UTC, pietrushnic commented
@miczyg1 @macpijan the reason to create DTS OS is avoiding container complexity. We should stop use containerization and solely rely on iPXE or USB booted DTS OS. The same thing should happen in validation.

2022-04-06 22:14 UTC, macpijan commented
agree

2022-07-11 10:07 UTC, closed without merging

2022-07-11 10:08 UTC, macpijan commented
Moved as a DTS feature.